---
- name: Install Dependencies
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    update_cache: true

- name: Get Docker script
  ansible.builtin.uri:
    url: https://get.docker.com
    dest: "/tmp/get-docker.sh"
    method: GET
    return_content: true

- name: Make script executable
  ansible.builtin.file:
    path: "/tmp/get-docker.sh"
    mode: "+x"

- name: Run script
  ansible.builtin.command: /tmp/get-docker.sh
  changed_when: true

- name: Start and enable Docker Service
  ansible.builtin.service:
    name: "docker"
    state: restarted
    enabled: true

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ vars.user }}"
    groups: "docker"
    append: true

- name: Create CapRover directory
  ansible.builtin.file:
    path: "/captain/data"
    state: directory
    recurse: true

- name: Create CapRover config file
  ansible.builtin.copy:
    dest: "/captain/data/config-override.json"
    content: "{\"skipVerifyingDomains\":\"true\"}"
    mode: preserve

- name: Run CapRover
  community.docker.docker_container:
    image: caprover/caprover
    name: caprover
    state: started
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
    env:
      ACCEPTED_TERMS: "true"
      MAIN_NODE_IP_ADDRESS: "{{ vars.ip_address }}"
      DOCKER_CLIENT_TIMEOUT: "120"
      COMPOSE_HTTP_TIMEOUT: "120"
    volumes:
      - /captain:/captain
      - /var/run/docker.sock:/var/run/docker.sock
